### PR TITLE
Update travis gcc version and add macox/clang test

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by patrickelectric** [comment]
It appears that something is wrong with macox clang, I can build in my linux machine with clang7 with no problems, I'll test in my mac to see what is going on.

**Comment by patrickelectric** [comment]
Yeap, I was able to replicate the issue in my macbook.

**Comment by patrickelectric** [comment]
@progsource 	fixed.

**Comment by progsource** [comment]
Thank you

**Pull request merged**
